### PR TITLE
What would expect GF nowadays

### PR DESCRIPTION
**Pull request by RosaWagner**
Hi
Since I don't work for GF on Monday-Tuesday, GF-wise I am already on holidays. So I wanted to quickly make the file as GF would expect them to match all their recent standards so we can move forward.

This font is for Workspace so I removed everything related to OTF build. 

The client wants italic instances in Workspace, so I separated the source file and removed the slant axis. I know we can slice the VF directly, but it often ends up with wrong metadata and didn't want to waste time in testing etc. We can reverse that, reunite the sources and make it all nice when I come back. [Nunito](https://github.com/googlefonts/nunito/tree/main/sources) is an example of process for that.

I simplified everything (repo/font data) and reduced to the essential needed here knowing that this is not the main source, and the actual font maintained is Inter. This was the quicker way for me to produce file that I can ship to GF.

To build the font, you need `gftools`, and from the sources dir: `gftools builder config.yaml`. It will generate the STAT table, the web fonts etc. From the QA report I generated on the released fonts, I couldn't see how to fix it all whilst preserving your build system.

You can either make a makefile again; you can see in our [template repo](https://github.com/googlefonts/googlefonts-project-template) how it is done for this kind of build method. This is [our documentation](https://googlefonts.github.io/gf-guide/index) in case you are wandering why spec has changed so much.

You can keep all of that in another branch for now it you want.

**Now the problem is that the font can't build because of orphaned components issue:**

Capture d’écran 2022-07-02 à 14 25 10

It is quite curious that this problem appears in the sources in your main branch and not in the binaries in the release package.

### CODE REVIEW

**Comment by RosaWagner** [comment]
Maybe you can try to turn back the file into glyphpackages (+update config file accordingly), but I am not sure it is supported by [gftools builder](https://googlefonts.github.io/gf-guide/build.html). It would be a good test case.

**Comment by rsms** [comment]
Wow, this is a massive diff.

> This font is for Workspace

Since we decided to make it an official public project maintained by me, I'm not sure that's the case anymore. Let's talk offline about this with the rest of the group :-)

Since I will be left with having to maintain this in the future (without compensation) I'd prefer it if we can keep the toolchain and source structure as-is with the addition of a script or make target for GF-specific builds. Matching the build process to standard Inter's will reduce the maintenance cost for me.

The changes (>2500 files affected) is a bit much for GitHub and I wasn't able to review it all. I suggest making a few separate PRs, one for each change. (For example one that adds a gftools config file and gf-build.sh script invoking gftools but does not alter source files.)

I'm curious why you changed the license?

Regarding component issues, when I'm opening the source file with the latest stable Glyphs release 3.1 (3133), I don't see any issues:

Screen Shot 2022-07-02 at 13 00 02

Screen Shot 2022-07-02 at 13 00 14

**Comment by RosaWagner** [comment]
The massive diff comes from turning glyphspackage to glyphs files, and renaming the src directory. Renaming the dir is really not necessary but the more standard it looks, the faster it is to automate the build and QA the repo.

I had the component issue when I opened the glyphspackage from the repo’s main branch in Glyphs. I am with the last cut edge version, so maybe there is a problem there.

The license doesn’t have the correct copyright string, and now a Fontbakery check make sure the content hasn’t been altered by checking the entire layout (and for that the repo has to use the GF license template). Also the trademark should be in a TRADEMARK.txt file separated from the OFL.txt. This all stuff we will have to go through to be able to update Inter on GF.

Anyway now it’s sunday, from tomorrow 3 out of 4 of us is out on holidays, so won’t be able to onboard it before we come back around the 20th. I was suggesting to do all of that in a separated branch just to be able to ship files now and see later how we can arrange the main branch so it’s compatible with your expectations.

**Comment by RosaWagner** [comment]
This is a Fontbakery report for the font in the release package. There is only one VF with a slant axis by the way.

## Fontbakery report

Fontbakery version: 0.8.9

<details><summary><b>[1] Family checks</b></summary><div><details><summary>ℹ <b>INFO:</b> Check axis ordering on the STAT table.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/axis_order">com.google.fonts/check/STAT/axis_order</a>)</summary><div>


* ℹ **INFO** From a total of 1 font files, 0 of them (0.00%) lack a STAT table.

	And these are the most common STAT axis orderings:
	('wght-slnt', 1) [code: summary]
</div></details><br></div></details><details><summary><b>[27] InterTight.var.ttf</b></summary><div><details><summary>💔 <b>ERROR:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>


* 💔 **ERROR** Failed with IndexError: list index out of range
</div></details><details><summary>💔 <b>ERROR:</b> Check name table: FONT_SUBFAMILY_NAME entries. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/subfamilyname">com.google.fonts/check/name/subfamilyname</a>)</summary><div>


* 💔 **ERROR** Failed with AttributeError: 'NoneType' object has no attribute 'toUnicode'
</div></details><details><summary>💔 <b>ERROR:</b> STAT table has Axis Value tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/stat.html#com.adobe.fonts/check/stat_has_axis_value_tables">com.adobe.fonts/check/stat_has_axis_value_tables</a>)</summary><div>


* 💔 **ERROR** Failed with AttributeError: 'NoneType' object has no attribute 'AxisValue'
</div></details><details><summary>🔥 <b>FAIL:</b> Checking file is named canonically. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename">com.google.fonts/check/canonical_filename</a>)</summary><div>


* 🔥 **FAIL** The file 'InterTight.var.ttf' must be renamed to 'InterTight[slnt,wght].ttf' according to the Google Fonts naming policy for variable fonts. [code: bad-varfont-filename]
</div></details><details><summary>🔥 <b>FAIL:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp">com.google.fonts/check/gasp</a>)</summary><div>


* 🔥 **FAIL** Font is missing the 'gasp' table. Try exporting the font with autohinting enabled.
If you are dealing with an unhinted font, it can be fixed by running the fonts through the command 'gftools fix-nonhinting'
GFTools is available at https://pypi.org/project/gftools/ [code: lacks-gasp]
</div></details><details><summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright">com.google.fonts/check/font_copyright</a>)</summary><div>


* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2022 The Inter Project Authors" [code: bad-notice-format]
</div></details><details><summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyf_nested_components">com.google.fonts/check/glyf_nested_components</a>)</summary><div>


* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* Adieresis
	* Atilde
	* Aringogonek
	* uni01DE
	* uni1EA0
	* uni1EAC
	* uni1EB6
	* Alphatonos
	* uni1F08
	* uni1F09 and 380 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-nested-components]
</div></details><details><summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout">com.google.fonts/check/smart_dropout</a>)</summary><div>


* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]
</div></details><details><summary>🔥 <b>FAIL:</b> A font repository should not include ZIP files (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/zip_files">com.google.fonts/check/repo/zip_files</a>)</summary><div>


* 🔥 **FAIL** Please do not host ZIP files on the project repository. These files were detected:
	* ./inter-tight-20220701-1.zip
	* ./inter-tight-main.zip
	* ./$RECYCLE.BIN/$RIW3UHL.zip
	* ./$RECYCLE.BIN/$IIW3UHL.zip and ./InterTight-20220701-131311.zip [code: zip-files]
</div></details><details><summary>🔥 <b>FAIL:</b> Check variable font instances have correct names (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names">com.google.fonts/check/varfont_instance_names</a>)</summary><div>


* 🔥 **FAIL** Following instances are not supported: 
	- Extra Light
	- Extra Light Italic
	- Semi Bold
	- Semi Bold Italic
	- Extra Bold
	- Extra Bold Italic

Further info can be found in our spec https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances [code: bad-instance-names]
</div></details><details><summary>🔥 <b>FAIL:</b> Validate STAT particle names and values match the fallback names in GFAxisRegistry.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/gf-axisregistry">com.google.fonts/check/STAT/gf-axisregistry</a>)</summary><div>


* 🔥 **FAIL** STAT table is missing Axis Value Records [code: missing-axis-values]
</div></details><details><summary>🔥 <b>FAIL:</b> Ensure variable fonts include an avar table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/mandatory_avar_table">com.google.fonts/check/mandatory_avar_table</a>)</summary><div>


* 🔥 **FAIL** This variable font does not have an avar table. [code: missing-avar]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent">com.google.fonts/check/family/win_ascent_and_descent</a>)</summary><div>


* 🔥 **FAIL** OS/2.usWinAscent value should be equal or greater than 2263, but got 1984 instead [code: ascent]
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 654, but got 494 instead. [code: descent]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking with fontTools.ttx (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/ttx-roundtrip">com.google.fonts/check/ttx-roundtrip</a>)</summary><div>


* 🔥 **FAIL** name id 2 missing from name table
* ℹ **INFO** While converting TTF into an XML file, ttx emited the messages listed below.
</div></details><details><summary>🔥 <b>FAIL:</b> Validates that when an instance record is included for the default instance, its subfamilyNameID value is set to either 2 or 17, and its postScriptNameID value is set to 6. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.adobe.fonts/check/varfont/valid_default_instance_nameids">com.adobe.fonts/check/varfont/valid_default_instance_nameids</a>)</summary><div>


* 🔥 **FAIL** 'Regular' instance has the same coordinates as the default instance; its subfamilyNameID should be either 2 or 17, instead of 280. [code: invalid-default-instance-subfamily-nameid:280]
</div></details><details><summary>⚠ <b>WARN:</b> License URL matches License text on name table? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url">com.google.fonts/check/name/license_url</a>)</summary><div>


* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=14] [code: http-in-license-info]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>


* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>


* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- _part.t_base
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure dotted circle glyph is present and can attach marks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle">com.google.fonts/check/dotted_circle</a>)</summary><div>


* ⚠ **WARN** No dotted circle glyph present [code: missing-dotted-circle]
</div></details><details><summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars">com.google.fonts/check/gdef_mark_chars</a>)</summary><div>


* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 uni0488 (U+0488), uni0489 (U+0489), uni20DD (U+20DD), uni20DE (U+20DE), uniFE20 (U+FE20), uniFE21 (U+FE21), uniFE27 (U+FE27) and uniFE28 (U+FE28) [code: mark-chars]
</div></details><details><summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss">com.google.fonts/check/outline_alignment_miss</a>)</summary><div>


* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:

	* a (U+0061): X=660.0,Y=1119.5 (should be at x-height 1118?)

	* three.sups (U+00B3): X=266.5,Y=1488.0 (should be at cap-height 1490?)

	* Aring (U+00C5): X=538.0,Y=1985.0 (should be at ascender 1984?)

	* Uring (U+016E): X=606.0,Y=1985.0 (should be at ascender 1984?)

	* Uogonek (U+0172): X=854.0,Y=2.0 (should be at baseline 0?)

	* uni0198 (U+0198): X=1046.5,Y=1490.5 (should be at cap-height 1490?)

	* Vcursive (U+01B2): X=690.0,Y=1492.0 (should be at cap-height 1490?)

	* uni01BA (U+01BA): X=332.0,Y=-2.0 (should be at baseline 0?)

	* uni01BD (U+01BD): X=394.0,Y=2.0 (should be at baseline 0?)

	* aturn (U+0250): X=400.0,Y=-1.5 (should be at baseline 0?) 

	* And 66 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-misalignments]
</div></details><details><summary>ℹ <b>INFO:</b> Show hinting filesize impact. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/hinting_impact">com.google.fonts/check/hinting_impact</a>)</summary><div>


* ℹ **INFO** Hinting filesize impact:

 |               | InterTight.var.ttf          |
 |:------------- | ---------------:|
 | Dehinted Size | 741.2kb |
 | Hinted Size   | 741.2kb   |
 | Increase      | -24 bytes      |
 | Change        | -0.0 %  |
 [code: size-impact]
</div></details><details><summary>ℹ <b>INFO:</b> Font has old ttfautohint applied? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint">com.google.fonts/check/old_ttfautohint</a>)</summary><div>


* ℹ **INFO** Could not detect which version of ttfautohint was used in this font. It is typically specified as a comment in the font version entries of the 'name' table. Such font version strings are currently: ['Version 4.000;git-4352fb8'] [code: version-not-detected]
</div></details><details><summary>ℹ <b>INFO:</b> EPAR table present in font? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/epar">com.google.fonts/check/epar</a>)</summary><div>


* ℹ **INFO** EPAR table not present in font. To learn more see https://github.com/googlefonts/fontbakery/issues/818 [code: lacks-EPAR]
</div></details><details><summary>ℹ <b>INFO:</b> Check for font-v versioning. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fontv">com.google.fonts/check/fontv</a>)</summary><div>


* ℹ **INFO** Version string is: "Version 4.000;git-4352fb8"
The version string must ideally include a git commit hash and either a "dev" or a "release" suffix such as in the example below:
"Version 1.3; git-0d08353-release" [code: bad-format]
</div></details><details><summary>ℹ <b>INFO:</b> Font contains all required tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/required_tables">com.google.fonts/check/required_tables</a>)</summary><div>


* ℹ **INFO** This font contains the following optional tables:

	- loca

	- GPOS 

	- And GSUB [code: optional-tables]
</div></details><details><summary>ℹ <b>INFO:</b> List all superfamily filepaths (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/superfamily/list">com.google.fonts/check/superfamily/list</a>)</summary><div>


* ℹ **INFO** . [code: family-path]
</div></details><br></div></details>
### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 3 | 12 | 6 | 108 | 7 | 99 | 0 |
| 1% | 5% | 3% | 46% | 3% | 42% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **PASS**
* **DEBUG**

**Comment by RosaWagner** [comment]
You can ignore the errors and these 2 fails:

- 🔥 FAIL: Validates that when an instance record is included for the default instance, its subfamilyNameID value is set to either 2 or 17, and its postScriptNameID value is set to 6. ([com.adobe.fonts/check/varfont/valid_default_instance_nameids](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.adobe.fonts/check/varfont/valid_default_instance_nameids))

- 🔥 FAIL: A font repository should not include ZIP files ([com.google.fonts/check/repo/zip_files](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/zip_files))

Building with [gftools builder](https://googlefonts.github.io/gf-guide/build.html#gftools-builder) would help closing most of the FAILS because it wraps several fix scripts in addition to Fontmake (with all needed filters arg). But I just tried with your current source, and the builder doesn't support glyphspackages (it can build from .designspace files though). You can go into my branch directly, the build should work in one line in the CLI (without the strange component issue that we can't figure the origin).

If you are reluctant to convert (which I understand completely): 
- Fontmake has several filters to decompose transformed components and flatten nested component.
- The STAT table can be patched to binaries using [gftools gen-stat](https://googlefonts.github.io/gf-guide/build.html#gen-stat).
- Instances should not have spaces: Extra Light > ExtraLight (just like GF's Inter published version)

**Pull request merged**
